language: python
os:
  - linux
branches:
  only:
  - master
  - stable
python:
  - "3.5"
before_install: "apt-get install -y python3-gdal"
# command to install dependencies
install: "python setup.py install"
# command to run tests
script: "python setup.py test"
