language: python
os:
  - linux
branches:
  only:
  - master
  - stable
python:
  - "3.5"
before_install:
  - "pip3 install conda"
  - "conda create -y --name test_env python=3.5 nose gdal"
  - "source activate test_env"
# command to install dependencies
install: "python3 setup.py install"
# command to run tests
script: "python3 setup.py test"
